name = "bebek-takip"
main = "worker.js"
compatibility_date = "2026-04-19"

[[kv_namespaces]]
binding = "BEBEK_KV"
id = "76a597e2104d463db6aa6dcec8991f14"

[ai]
binding = "AI"

[triggers]
crons = ["*/5 * * * *"]
